.TH DENV 1 denv\-0.14.0
.SH NAME
denv \- The dynamic environment command line interface
.SH SYNOPSIS
.P
.B denv 
.RI [\| commands \|]
.RI [\| options \|]
.RI <key>
.RI <value>
.SH DESCRIPTION
.P
.BR denv
Acts as a shared memory interface to store and retrieve variables. Useful as a global environment
for executing programs and for Inter-Process Communication (IPC) in shell scripting.
.SH COMMANDS
.P
.B help	
.br
	Displays help information.
.br
.br
.B version
.br
	Displays current version.
.br
.br
.B set
.br
	Sets a key\-value pair.
.br
.br
.B get
.br
	Retrieves the value associated with a key.
.br
.br
.B rm
.br
	Removes key\-value pair.
.br
.br
.B ls
.br
	Lists all keys.
.br
.br
.B drop
.br
	Peform the drop operation (deletes everything).
.br
.br
.B stats
.br
	Displays status information.
.br
.br
.B cleanup
.RS 4
Performs cleanup by removing freed values, useful after removing several variables.
.RE
.br
.B save
.br
	Saves denv memory to a file.
.br
.br
.B load
.br
	Loads denv memory from a file.
.br
.B await
.br
	Blocks execution until a specified key changes value.
.br
.B exec
.br
	Executes a program with environment variables stored in denv.
.SH EXAMPLES
.P
.B denv set
.IR current_path
.IR "$PWD"
.br
	Set a key named "current_path" with the "$PWD" value.
.br
.br
.B denv get 
.IR current_path
.br
	Get the value associated to the "current_path" key.
.br
.br
.B denv save
.IR save.denv
.br
	Save all denv variables to a file named "save.denv".
.br
.br
.B denv load
.IR save.denv
.br
.br
.B denv rm
.IR current_path
.br
	Remove the "current_path" key\-value pair.
.br
	Load from a file generated by denv.
.br
.br
.B denv daemon
.br
	Wait until shutdown or SIGTERM to save it's state to a file.
.br
.SH OPTIONS
.B -v
.B --version
.B version
.br
.br
.B -h
.B --help
.B help
.br
.br
.B set
.B \-b
.B <bind path>
.IR <variable name>
.IR <variable value>
.br
	Sets a variable at a specified bind path.
.br
.B set
.B \-e
.B <variable name>
.B <variable value>
.br
	Sets an environment variable.
.br
	\-e and \-b can be combinated: \-eb or \-be
.br
.B get
.B \-b
.B <bind path>
.B <variable name>
.br
	Gets a variable at a specified bind path.
.br
.B rm
.B \-b
.B <bind path>
.B <variable name>
.br
	Removes a variable at a specified bind path.
.br
.B drop
.B \-f
.br
	Force the drop operation (deletes everything) and doesn't prompt the user.
.br
.B drop
.B \-b
.B <bind path>
.br
	Drop operation at a specified bind path.
.br
	\-f and \-b can be combinated: \-fb or \-bf
.br
.B ls
.B \-b
.br
	List variables at a specified bind path.

.SH "SEE ALSO"
.BR shmat (3)
.BR shmctl (3)
.BR exec (3)
.IR "Section 2.7 XSI Interprocess Communication."
.SH BUGS
https://github.com/SrBurns-rep/denv/issues
.SH LICENSE
.B GPL-3.0
